### ISSUE TITLE
feat: implement tracking with posthog

### ISSUE THREAD

**Issue by alice-ang** [GECO-Project-App/facilitation-app#21]
Events we like to track: 
- [ ] Something 1
- [ ] Something 2

**Comment by eliasfaltin** [comment]
Here are the basics I can think of:

- [ ] Event for when a given exercise was started (Check-In Started / Check-Out started)
- [ ] Event for when a given exercise was completed (might be trickier since we allow people to "abandon" right now, and we don't have a dedicated "complete" button. ~~@aripuguh This might be something worth implementing into the design so we can, over time, show users how much the app helped them (you have done so and so many check-ins using the app)~~
- [ ] How long did an exercise session take (time between exercise start and end event or time between exercise start and exercise abandon event (clicking on the home screen or navigating back using the back buttons)?
- [ ] Create a survey that gets triggered when a user completes an exercise.

I don't know yet about the abandon vs complete edge case. I am unsure whether having a "complete" button solves that problem. People might still use the back or home button even though they completed the exercise or the complete button even though they just "clicked through" it. 

We can keep things as they are for now and track the time spent on the exercise. If a user only spends 30 seconds in the check-in exercise flow, it is unlikely that they used the app throughout the exercise.


- [ ] For a given exercise, we might do things like:
   - [ ] For check-in and check-out exercises, how often did a user "re-shuffle" the question before they advanced

- [ ] We should get Stuff like daily and weekly users automagically. It is the same with session recordings. It is the same with time spent in the app per user (session time).

But for now, we want to check if:
- anyone opens the app
- what do they do in the app (which exercises do they use, do they complete them or use them "for real" (spending some reasonable time in there and not just skipping through everything)
- did they like it / did the app provide value
